# Maintainer: mimobn <mimobn2004@gmail.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=radisk-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Terminal-based radial disk usage visualizer inspired by KDE FileLight"
url="https://github.com/mimobn/radisk"
license=("GPL-3.0-or-later")
arch=("x86_64")
provides=("radisk")
conflicts=("radisk")
depends=("gcc-libs")
source=("https://github.com/mimobn/radisk/releases/download/v$pkgver/radisk-$pkgver-x86_64.tar.gz")
sha256sums=("82c7962d868ecfc406c7aedd59f8b4814a3567d4a8d6ecad7d2cffc3579ec365")

package() {
    install -Dm755 radisk -t "$pkgdir/usr/bin"
}
